kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-role-binding
  namespace: dev
subjects:
- kind: User
  name: ravi
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: ""

